### PR TITLE
Add lowercased versions of the *_ROOT and other variables to ensure support for CMake package discovery

### PR DESCRIPTION
**Pull request by vyasr**
Other packages using CMake may rely on these variables to exist for discovery. I've aliased the key ones (INCLUDE, ROOT, and ROOT) that might be useful for other projects.

### CODE REVIEW

**Comment by vyasr** [comment]
CC @robertmaynard

**Comment by robertmaynard** [comment]
I think it is worthwhile to document in the commit message that <project>_ROOT for `find_package` is the CMake feature that we are enabling with this. Since that uses the case-sensitive name, we need to set the lower-case variables so that calls like `find_package(cudf)` work.

**Comment by vyasr** [comment]
Updated the PR title. @trxcllnt Is that sufficient? It looks like this repo might use merge commits for PRs rather than squash rebases so the PR title may not be the most visible in the commit history.

**Comment by trxcllnt** [comment]
@vyasr we're currently setting these in the [arguments passed to the configure step](https://github.com/trxcllnt/rapids-compose/blob/7e023eb7581a763cfac78612999920d12016df53/etc/bash-utils.sh#L339-L341) for each project.

Is there another reason they need to be set as envvars? Seems like having them set globally would mean explicit `cmake -B -S` would pick them up, which I'm not sure we want?

**Comment by vyasr** [comment]
I think that if we're in a compose container we would expect that, right? That's precisely the use case that I intended to support. I ran into this while trying to build [cudf's basic example](https://github.com/rapidsai/cudf/tree/branch-21.12/cpp/examples/basic) where it started cloning and rebuilding the entire cudf directory unexpectedly rather than using my build. That seems like undesirable behavior in a development environment like compose, would you disagree?

**Comment by trxcllnt** [comment]
Aside from needing to set up the global ccache compiler symlinks, I've tried to make it where running things in the compose container isn't any different than running something on a (properly configured) host linux install.

Generally I've tried to minimize the amount of hidden magic, so commands run in the container are largely portable to other environments. Any special magic happens only when you explicitly invoke the convenience functions i.e. `build-cudf-cpp` et. al.

So with that in mind `cmake -S . -B build/` should do the same thing it would do normally, but I'm open to changing that philosophy if that's not what people want.

**Comment by vyasr** [comment]
Hmm that's fair, I don't have a strong opinion here. I was surprised by the result because the fact that all the convenience commands inside compose "just work" as far as discovering the right dependencies, but I can see that being the cleaner choice. The number of people trying to build something other than a core RAPIDS library inside rapids-compose is probably limited. I'm fine with closing this PR and calibrating my expectations accordingly if you and @robertmaynard don't see a strong reason to support this use case out of the box.

**Comment by robertmaynard** [comment]
I think that the reasons provided by @trxcllnt for the overall design of rapids-compose should be kept, and we don't go forward with these changes.

It would be unfortunate to lose this information for other rapids-compose users. Would it be reasonable to look at placing information about using `<pkg>_ROOT cmake .....` somewhere in the rapids-compose documentation?

**Comment by vyasr** [comment]
@trxcllnt let us know what you think about adding the documentation @robertmaynard suggested. I'll close this PR now and we can add that separately.

**Pull request closed without merging**
