### PR TITLE
Remove notebooks from workspace

### PR DESCRIPTION
**Pull request by harrism**
The notebooks repo is just a collection of submodules to other RAPIDS repos and symlinks into the notebooks folder in each of those submodules.

Having all these submodules is a problem with the vscode source code provider view unless you disable submodule discovery (which a user might not want to disable).

Since this repo only adds symlinks, and causes fetching a duplicate of every RAPIDS repo, this
PR proposes removing the notebooks repo from the scripts and vscode workspace in rapids-compose.﻿

### CODE REVIEW

**Comment by harrism** [comment]
I considered adding a link to each RAPIDS repo's notebooks folder to the generated .vscode workspace, but TBH I don't think it's really necessary.  But perhaps there is some rapids-compose use case for the notebooks repository that I am missing.

**Comment by cwharris** [comment]
Having notebooks as part of compose has introduced a handful of intermittent issues that can take away from otherwise productive time, and I'm not sure the notebook repo itself is necessary. The jupyter server is convenient, though. If the notebooks are still available via jupyter, then I think we should remove the notebooks repository from compose, at _least_ until we have cross-project notebooks to work on. A notebook which depended on cuml + cusignal combo, for example, wouldn't belong to either of those repos individually (I guess this is what notebooks-contrib is for).

edit:

Actually, iirc, it is the notebooks-contrib repo that has the intermittent issues with building. What if we removed that as well?

**Comment by cwharris** [comment]
In addition to the current changes, `compose.yml` may also need adjustments.

**Comment by harrism** [comment]
@cwharris `notebooks-contrib` doesn't have anything to build AFAICT and doesn't have submodules, unlike `notebooks`.

**Comment by trxcllnt** [comment]
Now that I'm back home, I should have time to address this tonight :-)

**Review by trxcllnt — APPROVED** [review]

**Pull request merged**
